Agregué el feature de verificación de disponibilidad de habitaciones
Aziderius/Hotel_Reservation pull request #6
Opened 2023-09-08 02:15 UTC by Aziderius

2023-09-08 02:17 UTC, Aziderius commented
Todos los features principales ya están en el código. Próximamente trabajaré en que la aplicación pueda guardar los datos de más de 1 cliente para hacer reservaciones.

2023-09-08 02:46 UTC, EmmanEsp requested changes

2023-09-08 02:46 UTC, EmmanEsp commented on Hazzbin Hotel.py
> +print("Thanks to join us in Hazzbin Hotel!")
agrega una linea en blanco al final EOL(End Of Line)

2023-09-08 02:46 UTC, EmmanEsp commented on Hazzbin Hotel.py
>  #Funcion de Verificación de disponibilidad de habitación
Dejaste el comentario a proposito?

2023-09-08 02:46 UTC, EmmanEsp commented on Hazzbin Hotel.py
> +    if initial_date > limit:
ambas fechas, inicio y salida deben estar dentro del limite

2023-09-08 02:55 UTC, Aziderius commented on Hazzbin Hotel.py
>  #Funcion de Verificación de disponibilidad de habitación
No, olvidé borrarlo, estuve probando una función y ahí la tenía puesta. Borrare ese comentario

2023-09-10 01:32 UTC, EmmanEsp requested changes
Intenta seccionar todo lo que esta dentro del `while True:` en otras funciones, si por el momento no ves como organizarlo en mas funciones, dejalo así y ya que termine lo estructuras.

2023-09-10 01:32 UTC, EmmanEsp commented on Hazzbin_Hotel_List.py
> +        num_room = input("Please, write the room you want to reserve: ")
La persona no elige la habitacion, tu le asignas la primera habitacion disponible que encuentres, entre las fechas que haya pedido, dependiendo del tipo que haya elegido, de no haber disponible, preguntar si quiere elegir otro tipo de habitación.

2023-09-12 02:47 UTC, EmmanEsp approved these changes

2023-09-12 03:00 UTC, merged